console.log(JSON.parse(`{
    "WCEApp": true,
    "WCEVersion": "2.10",
    "WCEArch": "SH4",
    "Machine": "0x01A6",
    "MachineName": "SH4",
    "Timestamp": 906164277,
    "Date": "1998-09-19",
    "NumberOfSymbols": 0,
    "NumberOfSections": 5,
    "SizeOfOptionalHeader": 224,
    "Characteristics": {
      "IMAGE_FILE_RELOCS_STRIPPED": false,
      "IMAGE_FILE_EXECUTABLE_IMAGE": true,
      "IMAGE_FILE_LINE_NUMS_STRIPPED": true,
      "IMAGE_FILE_LOCAL_SYMS_STRIPPED": true,
      "IMAGE_FILE_AGGRESSIVE_WS_TRIM": false,
      "IMAGE_FILE_LARGE_ADDRESS_AWARE": false,
      "IMAGE_FILE_BYTES_REVERSED_LO": false,
      "IMAGE_FILE_32BIT_MACHINE": true,
      "IMAGE_FILE_DEBUG_STRIPPED": false,
      "IMAGE_FILE_REMOVABLE_RUN_FROM_SWAP": false,
      "IMAGE_FILE_NET_RUN_FROM_SWAP": false,
      "IMAGE_FILE_SYSTEM": false,
      "IMAGE_FILE_DLL": true,
      "IMAGE_FILE_UP_SYSTEM_ONLY": false,
      "IMAGE_FILE_BYTES_REVERSED_HI": false
    },
    "Magic": "0x010B",
    "MajorLinkerVersion": 5,
    "MinorLinkerVersion": 12,
    "LinkerVersion": "5.12",
    "SizeOfCode": 26624,
    "SizeOfInitializedData": 45056,
    "SizeOfUninitializedData": 0,
    "AddressOfEntryPoint": 28916,
    "BaseOfCode": 4096,
    "BaseOfData": 32768,
    "ImageBase": 268435456,
    "SectionAlignment": 4096,
    "FileAlignment": 512,
    "MajorOperatingSystemVersion": 4,
    "MinorOperatingSystemVersion": 0,
    "OperatingSystemVersion": "4.0",
    "MajorImageVersion": 0,
    "MinorImageVersion": 0,
    "ImageVersion": "0.0",
    "MajorSubsystemVersion": 2,
    "MinorSubsystemVersion": 10,
    "SubsystemVersion": "2.10",
    "SizeOfImage": 86016,
    "SizeOfHeaders": 1024,
    "CheckSum": 0,
    "Subsystem": 9,
    "DllCharacteristics": 0,
    "SizeOfStackReserve": 65536,
    "SizeOfStackCommit": 4096,
    "SizeOfHeapReserve": 1048576,
    "SizeOfHeapCommit": 4096,
    "LoaderFlags": 0,
    "NumberOfRvaAndSizes": 16,
    "DLLImports": [
      {
        "dllName": "ole32.dll",
        "functions": [
          "CLSIDFromProgID",
          "CoTaskMemFree",
          "StringFromCLSID",
          "CoCreateInstance"
        ]
      },
      {
        "dllName": "OLEAUT32.dll",
        "functions": [
          "DispGetParam",
          "SetErrorInfo",
          "LoadTypeLib",
          "VariantInit",
          "VariantClear",
          "SysFreeString",
          "SysStringLen",
          "SysAllocStringLen",
          "SysAllocString"
        ]
      },
      {
        "dllName": "COREDLL.dll",
        "functions": [
          74,
          1018,
          35,
          34,
          65,
          60,
          2006,
          2002,
          290,
          494,
          497,
          495,
          193,
          1167,
          548,
          172,
          549,
          553,
          550,
          1092,
          57,
          874,
          858,
          528,
          1095,
          682,
          530,
          1094,
          529,
          10,
          11,
          464,
          456,
          58,
          455,
          61,
          63,
          537,
          73,
          457,
          229,
          870,
          859,
          861,
          886,
          288,
          1043,
          230,
          33,
          1044,
          4,
          5,
          463,
          1047,
          56,
          1041,
          2,
          45,
          3,
          213,
          200,
          533,
          532
        ]
      }
    ],
    "versionInfo": {
      "FileDescription": "PVBHOST2 Module",
      "FileVersion": "06.00.8261",
      "InternalName": "PVBHOST2",
      "LegalCopyright": "Copyright 1998 Microsoft Corp.",
      "OLESelfRegister": "",
      "OriginalFilename": "PVBHOST2.DLL",
      "ProductName": "Visual Basic for Windows CE",
      "ProductVersion": "6.0"
    }
  }`));
  